format = """
[](#9A348E)\
$os\
$username\
$localip\
[](fg:#9A348E bg:#DA627D)\
$time\
[](fg:#DA627D bg:#FCA17D)\
$directory\
[](fg:#FCA17D bg:#86BBD8)\
$git_branch\
$git_status\
[](fg:#86BBD8 bg:#06969A)\
$python\
[](fg:#06969A bg:#33658A)\
$status\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#9A348E"
disabled = true

[os.symbols]
Linux = " "
Arch = " "
Gentoo = " "
Debian = " "
FreeBSD = " "
NixOS = " "
Raspbian = " "
Windows = " "
Macos = " "
Unknown = " "

[localip]
ssh_only = true
style = "bg:#9A348E"
format = '[@$localipv4 ]($style)'
disabled = false

[time]
time_format = "%R" # Hour:Minute Format
style = "bg:#DA627D"
format = '[ $time ]($style)'
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bg:#FCA17D"
format = "[ $path ]($style)"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# "Documents" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#86BBD8"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ]($style)'

[rust]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ]($style)'

[python]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[status]
style = "bg:#33658A"
format = '[ \[$status\]]($style)'
disabled = false
